export const UI_ACTIONS = {
  UPDATE_NAME: 'UPDATE_NAME',
  INCREMENT_COUNT: 'INCREMENT_COUNT',
  SET_REPOS: 'SET_REPOS',
  ADD_USER: 'ADD_USER',
  UPDATE_NAME: 'UPDATE_NAME',
  UPDATE_EMAIL: 'UPDATE_EMAIL'
};

export const TEST_ACTION = {
  ACTION_1: 'ACTION_1'
};
